[package]
name = "curd"
version = "1.0.0"
authors = ["H. Dale McBane <h.dale.mcbane@gmail.com>"]

[dependencies]
docopt = "0.8"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`
yaml-rust = "0.3"
