package execute

import (
	"fmt"
	"os"
	"path/filepath"
)

// bashCompletion is the bash completion script for curd/curr. It relies on the
// `curd completion` helper for dynamic command/keyword suggestions and on
// `curd ls -k` for curr's keyword completion.
const bashCompletion = `#!/usr/bin/env bash
# curd/curr bash completion. Generated by: curd completions bash

_completions_curd()
{
  COMPREPLY=()   # Array variable storing the possible completions.

  # keep the suggestions in a local variable
  local cur=${COMP_WORDS[COMP_CWORD]}
  local pre=${COMP_WORDS[COMP_CWORD - 1]}
  local arg="-W"
  if [ "$pre" == "--config" -o "$cur" == "--config" ]; then
    arg="-f -W"
  elif [ "$pre" == "--dir" -o "$cur" == "--dir" ]; then
    arg="-d -W"
  fi
  local suggestions=($(compgen $arg "$(curd completion -- ${COMP_WORDS[@]})" -- "$cur"))
  COMPREPLY=("${suggestions[@]}")

  return 0
}

complete -F _completions_curd curd

_completions_curr()
{
  COMPREPLY=()   # Array variable storing the possible completions.

  # keep the suggestions in a local variable
  local suggestions

  if [ ${#COMP_WORDS[@]} -le 2 ]; then
    suggestions=($(compgen -W "$(curd ls -k)" -- "${COMP_WORDS[1]}"))
  else
    return 0
  fi
  COMPREPLY=("${suggestions[@]}")

  return 0
}

complete -F _completions_curr curr
`

// zshCompletion is the zsh completion script for curd/curr. It reuses the
// `curd completion` helper for dynamic suggestions.
const zshCompletion = `#compdef curd curr
# curd/curr zsh completion. Generated by: curd completions zsh

_curd_complete() {
  local -a suggestions
  suggestions=(${(z)"$(curd completion -- $words)"})
  compadd -a suggestions
}

_curr_complete() {
  local -a keywords
  keywords=(${(z)"$(curd ls -k)"})
  compadd -a keywords
}

compdef _curd_complete curd
compdef _curr_complete curr
`

// fishCompletion is the fish completion script for curd/curr. It reuses the
// `curd completion` helper for dynamic suggestions.
const fishCompletion = `# curd/curr fish completion. Generated by: curd completions fish

function __curd_complete
    set -l tokens (commandline -opc)
    set -l current (commandline -ct)
    curd completion -- $tokens $current | string split ' '
end

function __curr_complete
    curd ls -k | string split ' '
end

complete -c curd -f -a '(__curd_complete)'
complete -c curr -f -a '(__curr_complete)'
`

// detectShell returns the base name of the shell referenced by the SHELL
// environment variable (e.g. "/usr/bin/fish" -> "fish"). It returns an empty
// string when SHELL is not set.
func detectShell() string {
	sh := os.Getenv("SHELL")
	if sh == "" {
		return ""
	}
	return filepath.Base(sh)
}

// GenerateCompletions prints the shell completion script for the requested
// shell to stdout. When shell is empty, it is detected from the SHELL
// environment variable. An error is returned for unsupported or undetectable
// shells.
func GenerateCompletions(shell string) error {
	if shell == "" {
		shell = detectShell()
	}

	switch shell {
	case "bash":
		fmt.Print(bashCompletion)
	case "zsh":
		fmt.Print(zshCompletion)
	case "fish":
		fmt.Print(fishCompletion)
	case "":
		return fmt.Errorf("could not detect shell: set the SHELL environment variable or specify one of bash, fish, zsh")
	default:
		return fmt.Errorf("unsupported shell %q: supported shells are bash, fish, zsh", shell)
	}
	return nil
}
